### ISSUE TITLE
add css to footer

### ISSUE THREAD

**Issue by tarunnayakar** [tarunnayakar/portfolio-tarun#1]

**Comment by 08Uzair** [comment]
Please Assign this to me

**Comment by tarunnayakar** [comment]
> Please Assign this to me

If this is for hacktoberfest u can edit or do anything ur pr will be acceptable

**Comment by 08Uzair** [comment]
#1 I had done the PR please check it as soon as possible and give the review

**Comment by tarunnayakar** [comment]
> #1 I had done the PR please check it as soon as possible and give the review

Can u share some screen shots

**Comment by 08Uzair** [comment]
![image](https://github.com/tarunnayakar/portfolio-tarun/assets/121750611/f8851466-12ea-42a3-bc51-4a36cddd9028)

**Comment by tarunnayakar** [comment]
> ![image](https://user-images.githubusercontent.com/121750611/277241107-f8851466-12ea-42a3-bc51-4a36cddd9028.png)

It's merged  thank you for contributing

**Comment by 08Uzair** [comment]
ok
